/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js and checked in so `next build` never rewrites the
// working tree. Do not edit it.
